apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
---
apiVersion: v1
kind: Service
metadata:
  name: fluentd-forward
  labels:
    name: fluentd-stdout
spec:
  selector:
    name: fluentd-stdout
  ports:
    - protocol: TCP
      port: 24224
      targetPort: fluentd-forward
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-stdout-conf
data:
  fluent.conf: |
    # In v1 configuration, type and id are @ prefix parameters.
    # @type and @id are recommended. type and id are still available for backward compatibility
    
    ## built-in TCP input
    ## $ echo <json> | fluent-cat <tag>
    <source>
      @type forward
      @id forward_input
    
      port 24224
    </source>
    
    ## built-in UNIX socket input
    #<source>
    #  @type unix
    #</source>
    
    # HTTP input
    # http://localhost:8888/<tag>?json=<json>
    <source>
      @type http
      @id http_input
    
      port 8888
    </source>
    
    # Listen HTTP for monitoring
    # http://localhost:24220/api/plugins
    # http://localhost:24220/api/plugins?type=TYPE
    # http://localhost:24220/api/plugins?tag=MYTAG
    <source>
      @type monitor_agent
      @id monitor_agent_input
    
      port 24220
    </source>
    
    ## match fluent's internal events
    #<match fluent.**>
    #  @type null
    #</match>
    
    # match not matched logs and write to file
    <match **>
      @type stdout
      @id stdout
    </match>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-stdout
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fluentd-stdout
  template:
    metadata:
      annotations:
      labels:
        name: fluentd-stdout
    spec:
      containers:
      - command:
        - scl
        - enable
        - rh-ruby25
        - -- 
        - fluentd
        - -c
        - /etc/fluentd/fluent.conf
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: registry.redhat.io/openshift4/ose-logging-fluentd
        imagePullPolicy: IfNotPresent
        name: fluentd-stdout
        resources: {}
        volumeMounts:
        - name: fluent-stdout-conf
          mountPath: /etc/fluentd/fluent.conf
          subPath: "fluent.conf"
        ports:
        - containerPort: 24224
          name: fluentd-forward
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      securityContext: {}
      serviceAccount: fluentd
      serviceAccountName: fluentd
      volumes:
      - name: fluent-stdout-conf
        configMap:
          name: fluent-stdout-conf
