apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-stdout
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fluentd-stdout
  template:
    metadata:
      annotations:
      labels:
        name: fluentd-stdout
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - sleep infinity
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: registry.redhat.io/openshift4/ose-logging-fluentd
        imagePullPolicy: IfNotPresent
        name: fluentd-stdout
        resources: {}
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      securityContext: {}
      serviceAccount: fluentd
      serviceAccountName: fluentd
