apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-stdout-conf
data:
  fluent.conf: |
    # In v1 configuration, type and id are @ prefix parameters.
    # @type and @id are recommended. type and id are still available for backward compatibility
    
    ## built-in TCP input
    ## $ echo <json> | fluent-cat <tag>
    <source>
      @type forward
      @id forward_input
    
      port 24224
    </source>
    
    ## built-in UNIX socket input
    #<source>
    #  @type unix
    #</source>
    
    # HTTP input
    # http://localhost:8888/<tag>?json=<json>
    <source>
      @type http
      @id http_input
    
      port 8888
    </source>
    
    # Listen HTTP for monitoring
    # http://localhost:24220/api/plugins
    # http://localhost:24220/api/plugins?type=TYPE
    # http://localhost:24220/api/plugins?tag=MYTAG
    <source>
      @type monitor_agent
      @id monitor_agent_input
    
      port 24220
    </source>
    
    ## match fluent's internal events
    #<match fluent.**>
    #  @type null
    #</match>
    
    # match not matched logs and write to file
    <match **>
      @type stdout
      @id stdout
    </match>
