apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  collection:
    logs:
      fluentd:
        resources:
          limits:
            memory: 50Mi
          requests:
            memory: 50Mi
      type: fluentd
  curation:
    curator:
      schedule: 30 3 * * *
    type: curator
  logStore:
    elasticsearch:
      nodeCount: 3
      redundancyPolicy: SingleRedundancy
      resources:
        limits:
          memory: 2Gi
        requests:
          memory: 2Gi
      storage:
        size: 8G
        storageClassName: managed-nfs-storage
    retentionPolicy:
      application:
        maxAge: 7d
    type: elasticsearch
  managementState: Managed
  visualization:
    kibana:
      replicas: 1
      resources:
        limits:
          memory: 200Mi
        requests:
          memory: 200Mi
    type: kibana
